eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

---
spring:
  profiles: subject
  application:
    name: subject
words: I,You,He,She,It

---
spring:
  profiles: verb
  application:
    name: verb
words: ran,knew,had,saw,bought

---
spring:
  profiles: article
  application:
    name: article
words: a,the

---
spring:
  profiles: adjetive
  application:
    name: adjetive
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: noun
  application:
    name: noun
words: boat,book,vote,seat,backpack,partition,groundhog

---
spring:
  profiles: cold-noun
  application:
    name: cold-noun
words: icicle,refrigerator,blizzard,snowball
